# Bigram Typing Preference Study processing and analysis configuration

#-------------------------------------------------------------------------------
# Input/output settings
#-------------------------------------------------------------------------------
data:
  # input / output directory:
  input_dir: "input/summary_data/nonProlific_studies"
  # process_data.py output / analyze_...py input:
  filtered_data_file: "output/tables/processed_consistent_choices.csv" 

#-------------------------------------------------------------------------------
# process_summary_data.py settings
#-------------------------------------------------------------------------------
process:
  # Filter users by inconsistent or improbable choice thresholds:
  # Improbable choices (left typing hand) in the easy_choice_pairs_file
  # good_choice,bad_choice
  # fr,vr  # same finger same direction 1 vs. 2 off home row (studies 1-7)
  # aq,zq  # same finger same direction 1 vs. 2 off home row (study 2A)
  # fd,ce  # 2 strongest fingers home row vs. skip home row with same finger (study 1)
  # df,qz  # 2 strongest fingers home row vs. skip home row with weakest finger (study 6)
  # df,ex  # 2 strongest fingers home row vs. skip home row (study 6)
  # fd,ez  # 2 strongest fingers home row vs. skip home row (study 6)
  # fd,qz  # 2 strongest fingers home row vs. skip home row with weakest finger (study 7)
  # df,wz  # 2 strongest fingers home row vs. skip home row with weakest fingers (study 7)
  # ff,aa  # strongest vs. weakest finger (studies 8-9)
  filter_users_by_num_improbable_choices: True
  improbable_threshold: 0 # if 0, at least one improbable bigram chosen both times
 
  # Filter users by inconsistent choices (choosing both sides of a bigram pair):
  filter_users_by_percent_strong_inconsistencies: True
  strong_inconsistent_threshold: 50  # Flag users with at least this percent of strongly inconsistent choices

  # Filter users by improbable slider behavior (consecutive side bias or close-to-zeros):
  streak_side_percent: 50  # Flag users with consecutive same-side selections
  percent_close_to_zero: 90  # Flag users with this percent of selections close to zero
  distance_close_to_zero: 10  # Consider values within this distance of zero as "close to zero" (max 100)

  # Filter rows with *per user* single-presentation bigram pairs or inconsistent bigram pair choices away from zero:
  filter_single_presentations: False
  filter_inconsistent_choices_away_from_zero: True
  zero_threshold: 50  # Consider absolute values greater than this as "away from zero" (max 100)

  # Filter rows with bigrams containing any of the following letters:
  filter_letters: [] #['t', 'g', 'b']

#-------------------------------------------------------------------------------
# analyze_frequency_speed_preference.py settings
#-------------------------------------------------------------------------------
analysis:
  # Participant-level settings
  min_trials_per_participant: 10
  outlier_threshold_sd: 3.0
  min_bigram_occurrences: 5
  
  # Statistical settings
  bootstrap_iterations: 1000
  confidence_level: 0.95
  
  # Time difference analysis
  max_time_ms: 3000
  normalize_method: "median"  # Options: median, mean
  n_quantiles: 5
  
  # Frequency analysis
  frequency_transform: "log10"  # Options: log10, log2, none

  # Subdirectory names
  subdirs:
    typing_time_vs_preference: "typing_time_vs_preference"
    typing_time_vs_frequency: "typing_time_vs_frequency"
    preference_prediction: "preference_prediction"
    keyboard_ergonomics: "keyboard_ergonomics"

#-------------------------------------------------------------------------------
# analyze_preferred_positions_transitions.py settings (Bradley-Terry analysis)
#-------------------------------------------------------------------------------
position_transition_analysis:
  # Enable/disable the Bradley-Terry position and transition analysis
  enabled: true
  
  # Statistical settings
  alpha_level: 0.05                    # Significance level for statistical tests
  correction_method: 'fdr_bh'          # Multiple comparison correction: 'fdr_bh' or 'bonferroni'
  bootstrap_iterations: 1000           # For bootstrap confidence intervals
  confidence_level: 0.95               # For confidence intervals
  
  # Bradley-Terry model settings
  max_iterations: 1000                 # Maximum iterations for model fitting
  convergence_tolerance: 0.000001      # Convergence criterion (not currently used)
  regularization: 0.0000000001         # Small value to prevent numerical issues (1e-10)
  
  # Minimum sample size requirements
  min_key_comparisons: 5               # Minimum comparisons needed for key analysis
  min_transition_comparisons: 10       # Minimum comparisons needed for transition analysis
  min_finger_comparisons: 3            # Minimum comparisons per finger for reliable ranking
  
  # Practical significance thresholds
  key_effect_thresholds:
    negligible: 0.05                   # < 5 percentage points difference
    small: 0.15                        # 5-15 percentage points difference
    medium: 0.30                       # 15-30 percentage points difference
    # large: > 30 percentage points
    
  transition_effect_thresholds:
    negligible: 0.03                   # < 3 percentage points difference
    small: 0.10                        # 3-10 percentage points difference  
    medium: 0.25                       # 10-25 percentage points difference
    # large: > 25 percentage points
  
  # Confidence level assessment criteria
  confidence_criteria:
    definitive:
      min_significant_pairs: 0.70      # At least 70% of pairs statistically significant
      min_large_effects: 0.50          # At least 50% of pairs show large effects
    probable:
      min_significant_pairs: 0.50      # At least 50% of pairs statistically significant
      min_large_effects: 0.30          # At least 30% of pairs show large effects
    suggestive:
      min_significant_pairs: 0.30      # At least 30% of pairs statistically significant
      min_large_effects: 0.20          # At least 20% of pairs show large effects
    # inconclusive: below suggestive thresholds
  
  # Key selection settings
  analyze_keys: 'left_hand_15'         # Options: 'home_block_12', 'left_hand_15', 'all_letters'
  # left_hand_15: QWERTASDFGZXCVB (recommended)
  # home_block_12: QWERASDFZXCV (original)
  # all_letters: All 26 letters (if you want full coverage)
  
  # Output settings
  generate_visualizations: true        # Create plots and figures
  generate_detailed_report: true       # Create comprehensive text report
  save_raw_results: true              # Save complete JSON results and CSV tables
  
  # Visualization settings
  figure_dpi: 300                     # Resolution for saved figures
  figure_format: ['png']              # Output formats for figures (png, pdf, svg)
  heatmap_colormap: 'RdYlGn'          # Colormap for preference heatmaps
  ranking_plot_style: 'horizontal'    # 'horizontal' or 'vertical' bar plots

#-------------------------------------------------------------------------------
# Logging settings
#-------------------------------------------------------------------------------
logging:
  level: "INFO"
  file: "input/logs/bigram_analysis.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

#-------------------------------------------------------------------------------
# Visualization settings
#-------------------------------------------------------------------------------
visualization:
  dpi: 300
  figsize: [10, 6]
  style: "default"
  colors:
    primary: "#1f77b4"
    secondary: "#ff7f0e"
    error_bars: "#2ca02c"
    regression: "#9467bd"
    
  plots:
    time_diff:
      figsize: [12, 8]
      alpha: 0.5
      grid_alpha: 0.3
      bins: 30
      confidence_alpha: 0.8
      error_alpha: 0.2
      error_capsize: 5
      
    frequency:
      figsize: [12, 8]
      scatter_alpha: 0.6
      error_alpha: 0.2
      regression_alpha: 0.7
      label_fontsize: 8
      grid_alpha: 0.3
      
    prediction:
      figsize: [10, 6]
      hist_bins: 20
      bar_alpha: 0.8
      error_capsize: 5
      grid_alpha: 0.3
      
    distribution:
      figsize: [15, 10]
      grid_alpha: 0.3
      legend_fontsize: 10
      title_fontsize: 16
      label_fontsize: 12